highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Arnob Kundu's Resume
name: Arnob Kundu
email: arnob.joy013@gmail.com
email_full: mailto:arnob.joy013@gmail.com
website: github.io/Arnob013
website_full: https://jekyllt.github.io/sustain
github: trending
twitter: twitter
tel: +358 413 154772
tel_full: tel:+358413154772
google_maps: 'https://www.google.fi/maps/place/Ter%C3%A4skatu+2,+33720+Tampere'
address:
  street: Teräskatu 2
  postcode: 33720
  city: Tampere
  country: Finland
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
